export const TrainingTestIds = {
    MODAL_ERROR: 'modal-no-review',
    MODAL_ERROR_BUTTON_CLOSE: 'modal-error-user-training-button-close',
    MODAL_ERROR_TITLE: 'modal-error-user-training-title',
    MODAL_ERROR_SUBTITLE: 'modal-error-user-training-subtitle',
    MODAL_ERROR_BUTTON: 'modal-error-user-training-button',
    MODAL_CREATE_TRAINING: 'modal-create-training',
    MODAL_CREATE_EXERCISE: 'modal-create-exercise',
    MODAL_EXERCISE_BUTTON_CLOSE: 'modal-exercise-training-button-close',
    MODAL_CREATE_EXERCISE_SELECT: 'modal-create-exercise-select',
    MODAL_CREATE_BUTTON_CLOSE: 'modal-create-training-button-close',
    MODAL_UPDATE_EDIT_BUTTON: 'modal-update-training-edit-button',
    MODAL_DRAWER_RIGHT: 'modal-drawer-right',
    MODAL_DRAWER_RIGHT_BUTTON_CLOSE: 'modal-drawer-right-button-close',
    MODAL_DRAWER_INPUT_EXERCISE: 'modal-drawer-right-input-exercise',
    MODAL_DRAWER_CHECKBOX_EXERCISE: 'modal-drawer-right-checkbox-exercise',
    MODAL_DRAWER_INPUT_APPROACH: 'modal-drawer-right-input-approach',
    MODAL_DRAWER_INPUT_WEIGHT: 'modal-drawer-right-input-weight',
    MODAL_DRAWER_INPUT_QUANTITY: 'modal-drawer-right-input-quantity',
};
