export enum ApiEndpoints {
    AUTH_GOOGLE = '/auth/google',
    AUTH_LOGIN = '/auth/login',
    AUTH_REGISTRATION = '/auth/registration',
    AUTH_CHECK_EMAIL = '/auth/check-email',
    AUTH_CONFIRM_EMAIL = '/auth/confirm-email',
    AUTH_CHANGE_PASSWORD = '/auth/change-password',
    CATALOGS_TRAINING_LIST = '/catalogs/training-list',
    CATALOGS_TARIFF_LIST = '/catalogs/tariff-list',
    CATALOGS_TRAINING_PALS = '/catalogs/training-pals',
    CATALOGS_USER_JOIN_TRAAINING_LIST = '/catalogs/user-joint-training-list',
    FEEDBACK = '/feedback',
    TRAINING = '/training',
    USER_ME = '/user/me',
    UPLOAD_IMAGE = '/upload-image',
    USER = '/user',
    INVITE = '/invite',
}
