export const TRAINING_TEST_IDS = {
    modalNoReview: 'modal-no-review',
    modalErrorButtonClose: 'modal-error-user-training-button-close',
    modalErrorTitle: 'modal-error-user-training-title',
    modalErrorSubtitle: 'modal-error-user-training-subtitle',
    modalErrorButton: 'modal-error-user-training-button',
    modalCreateTraining: 'modal-create-training',
    modalCreateExercise: 'modal-create-exercise',
    modalExerciseButtonClose: 'modal-exercise-training-button-close',
    modalCreateExerciseSelect: 'modal-create-exercise-select',
    modalCreateButtonClose: 'modal-create-training-button-close',
    modalUpdateEditButton: 'modal-update-training-edit-button',
    modalDrawer: 'modal-drawer-right',
    modalDrawerButtonClose: 'modal-drawer-right-button-close',
    modalDrawerInputExercise: 'modal-drawer-right-input-exercise',
    modalDrawerCheckboxExercise: 'modal-drawer-right-checkbox-exercise',
    modalDrawerInputApproach: 'modal-drawer-right-input-approach',
    modalDrawerInputWeight: 'modal-drawer-right-input-weight',
    modalDrawerInputQuantity: 'modal-drawer-right-input-quantity',
};
