export const AUTH_TEST_IDS = {
    loginEmail: 'login-email',
    loginPassword: 'login-password',
    loginRemember: 'login-remember',
    loginForgotButton: 'login-forgot-button',
    loginSubmitButton: 'login-submit-button',
    registrationEmail: 'registration-email',
    registrationPassword: 'registration-password',
    registrationConfirmPassword: 'registration-confirm-password',
    registrationSubmitButton: 'registration-submit-button',
    changePassword: 'change-password',
    changeConfirmPassword: 'change-confirm-password',
    changeSubmitButton: 'change-submit-button',
    verificationInput: 'verification-input',
    registrationEnterButton: 'registration-enter-button',
    registrationRetryButton: 'registration-retry-button',
    registrationBackButton: 'registration-back-button',
    loginRetryButton: 'login-retry-button',
    checkRetryButton: 'check-retry-button',
    checkBackButton: 'check-back-button',
    changeRetryButton: 'change-retry-button',
    changeEntryButton: 'change-entry-button',
}
