export enum AuthTestIds {
    LOGIN_EMAIL = 'login-email',
    LOGIN_PASSWORD = 'login-password',
    LOGIN_REMEMBER = 'login-remember',
    LOGIN_FORGOT_BUTTON = 'login-forgot-button',
    LOGIN_SUBMIT_BUTTON = 'login-submit-button',
    REGISTRATION_EMAIL = 'registration-email',
    REGISTRATION_PASSWORD = 'registration-password',
    REGISTRATION_PASSWORD_CONFIRM = 'registration-confirm-password',
    REGISTRATION_SUBMIT_BUTTON = 'registration-submit-button',
    CHANGE_PASSWORD = 'change-password',
    CHANGE_PASSWORD_CONFIRM = 'change-confirm-password',
    CHANGE_SUBMIT_BUTTON = 'change-submit-button',
    VERIFICATION_INPUT = 'verification-input',
    REGISTRATION_ENTER_BUTTON = 'registration-enter-button',
    REGISTRATION_RETRY_BUTTON = 'registration-retry-button',
    REGISTRATION_BACK_BUTTON = 'registration-back-button',
    LOGIN_RETRY_BUTTON = 'login-retry-button',
    CHECK_RETRY_BUTTON = 'check-retry-button',
    CHECK_BACK_BUTTON = 'check-back-button',
    CHANGE_RETRY_BUTTON = 'change-retry-button',
    CHANGE_ENTRY_BUTTON = 'change-entry-button',
}
